#!/bin/bash

## to be used with the following syntax:
## printf '${color}foobar${end}'
## echo -e '${color}foobar${end}'

# foreground colors ([color])
black=$'\e[30m'
red=$'\e[31m'
green=$'\e[32m'
yellow=$'\e[33m'
blue=$'\e[34m'
magenta=$'\e[35m'
cyan=$'\e[36m'
lgray=$'\e[37m'
dgray=$'\e[90m'
lred=$'\e[91m'
lgreen=$'\e[92m'
lyellow=$'\e[93m'
lblue=$'\e[94m'
lmagenta=$'\e[95m'
lcyan=$'\e[96m'
white=$'\e[97m'
end=$'\e[39m'

# background colors ([color]b)
blackb=$'\e[40m'
redb=$'\e[41m'
greenb=$'\e[42m'
yellowb=$'\e[43m'
blueb=$'\e[44m'
magentab=$'\e[45m'
cyanb=$'\e[46m'
lgrayb=$'\e[47m'
dgrayb=$'\e[100m'
lredb=$'\e[101m'
lgreenb=$'\e[102m'
lyellowb=$'\e[103m'
lblueb=$'\e[104m'
lmagentab=$'\e[105m'
lcyanb=$'\e[106m'
whiteb=$'\e[107m'
endb=$'\e[49m'
